name: Building
on:
  push:
    branches:
      - master
jobs:
  clone:
    runs-on: unbuntu-latest
    steps:
        uses: actions/checkout@v1
        run: echo "Hello"
  install:
    needs: clone
    runs-on: ubuntu-latest
    steps:
        uses: actions/setup-node@v1
        with:
          node-version: 10
        run: npm install
