name: Building
on:
  push:
    branches:
      - master
jobs:
  clone:
    runs-on: unbuntu-latest
    steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 1
          run: echo "Hello"
  install:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v1
        - run: ls
