name: Building
on:
  push:
    branches:
      - master
jobs:
  initialize:
    runs-on: unbuntu-latest
    steps:
        - run: echo "$PATH"
  install:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@master
        - run: echo "$PATH"
