name: Building
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: cd vue-redesign && npm install
