name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
        run: |
          ls -l
    steps:
      - name: build
      - uses: actions/node-setup@Master
        run: |
          npm -v
          cd vue-redesign
          npm install
