name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
        run: |
          ls -l
          cd vue-redesign
          ls -l
          npm -v
