name: CI

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: checkout
        run: |
          ls -l
      - uses: actions/setup-node@master
      - name: build
        run: |
          npm -v
          cd vue-redesign
          ls -l
          npm install
