name: Building
on:
  push:
    branches:
      - master
jobs:
  build:
  runs-on: unbuntu-latest
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 10
      run: npm install
